{
 "title": "Cluster capacity",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "query": "label_values(env)" }
  ]
 },
 "panels": [
  {
   "title": "Node CPU allocated",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$env(w).+\"}) by(node) / \navg(kube_node_status_allocatable_cpu_cores{node=~\"$env(w).+\"}) by(node)\n* 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=\"$env\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU allocated history",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{node=~\"$env(w).+\"}) by(node) / \navg(kube_node_status_allocatable_cpu_cores{node=~\"$env(w).+\"}) by(node)\n* 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Node memory allocated",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$env(w).+\"}) by(node) /\navg(kube_node_status_allocatable_memory_bytes) by(node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 10, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{env=\"$env\"} - node_memory_MemAvailable{env=\"$env\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory allocated history",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{node=~\"$env(w).+\"}) by(node) /\navg(kube_node_status_allocatable_memory_bytes) by(node) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Datastore usage SAS",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_resourcequota{env=\"$env\",resource=~\"sas.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"} !=0",
     "legendFormat": "{{namespace}}: {{resource}}"
    },
    {
     "expr": "sum(kube_resourcequota{env=\"$env\",resource=~\"sas.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"})",
     "legendFormat": "Requests Summary"
    },
    {
     "expr": "sum(vmware_datastore_capacity_size{ds_name=~\"sas-($env)-ps\"}) by(ds_name)",
     "legendFormat": "{{ ds_name }} capacity"
    },
    {
     "expr": "sum(vmware_datastore_provisoned_size{ds_name=~\"sas-($env)-ps\"}) by(ds_name)",
     "legendFormat": "{{ ds_name }} provisioned"
    },
    {
     "expr": "sum(vmware_datastore_freespace_size{ds_name=~\"sas-($env)-ps\"}) by(ds_name)",
     "legendFormat": "{{ ds_name }} free"
    }
   ]
  },
  {
   "title": "Datastore usage SSD",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kube_resourcequota{env=\"$env\",resource=~\"ssd.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"} !=0",
     "legendFormat": "{{namespace}}: {{resource}}"
    },
    {
     "expr": "sum(kube_resourcequota{env=\"$env\",resource=~\"ssd.storageclass.storage.k8s.io/requests.storage\",type=\"hard\"})",
     "legendFormat": "Requests Summary"
    },
    {
     "expr": "sum(vmware_datastore_capacity_size{ds_name=~\"ssd-($env)-ps\"}) by(ds_name)",
     "legendFormat": "{{ ds_name }} capacity"
    },
    {
     "expr": "sum(vmware_datastore_provisoned_size{ds_name=~\"ssd-($env)-ps\"}) by(ds_name)",
     "legendFormat": "{{ ds_name }} provisioned"
    },
    {
     "expr": "sum(vmware_datastore_freespace_size{ds_name=~\"ssd-($env)-ps\"}) by(ds_name)",
     "legendFormat": "{{ ds_name }} free"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } }
 ]
}