{
 "title": "Clusters brief",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU allocated",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by(env) / \nsum(kube_node_status_allocatable_cpu_cores) by(env)\n* 100",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "(count(count(node_cpu) by (instance,cpu,env)) by(env) - sum(sum(rate(node_cpu{mode='idle'}[2m])) by (instance,mode,env)) by (env)) /\ncount(count(node_cpu) by (instance,cpu,env)) by(env) * 100",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Allocated memory",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by(env) / sum(kube_node_status_allocatable_memory_bytes) by(env) * 100",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(sum(node_memory_MemTotal) by (env) - sum(node_memory_MemAvailable) by(env)) / sum(node_memory_MemTotal) by (env) * 100",
     "legendFormat": "{{env}}"
    }
   ]
  }
 ]
}