{
 "title": "Federation",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Target pool sync",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "prometheus_target_scrape_pool_sync_total",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "ENV status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "avg(up) by(env)", "legendFormat": "{{env}}" }
   ]
  },
  {
   "title": "Targets Down",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100  * (count by(job,env) (up == 0) / count by(job,env) (up)) > 10",
     "legendFormat": "{{env}}: {{job}}"
    }
   ]
  }
 ]
}