{
 "title": "Node Metrics Detailed",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "nodename",
    "query": "label_values(node_uname_info{ env=~\"$ENV\"}, nodename)"
   },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_uname_info{nodename=\"$nodename\", env=~\"$ENV\"}, instance)"
   },
   { "name": "ENV", "label": "env", "query": "label_values(env)" },
   {
    "name": "node_ip",
    "label": "Node",
    "query": "label_values(node_uname_info{nodename=\"$nodename\", env=~\"$ENV\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Basic CPU / Mem / Disk Gauge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(count(node_cpu{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Load (1m avg) %",
   "type": "graph",
   "description": "Busy state of all CPU cores together (1 min average)",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1{instance=~\"$node\",env=~\"$ENV\"}) /  count(count(node_cpu{instance=~\"$node\",env=~\"$ENV\"}) by (cpu)) * 100",
     "legendFormat": "avg load1"
    }
   ]
  },
  {
   "title": "Used RAM Memory",
   "type": "graph",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable{instance=~\"$node\"} * 100) / node_memory_MemTotal{instance=~\"$node\"})",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Used filesystems",
   "type": "graph",
   "description": "Used Root FS",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(node_filesystem_avail{instance=~\"$node\",mountpoint=\"/host/root\"}) * 100) / avg(node_filesystem_size{instance=~\"$node\",mountpoint=\"/host/root\"})\nor\n100 - (avg(node_filesystem_avail{instance=~\"$node\",mountpoint=\"/\",fstype=\"rootfs\"}) * 100) / avg(node_filesystem_size{instance=~\"$node\",mountpoint=\"/\",fstype=\"rootfs\"})",
     "legendFormat": "/host/root"
    },
    {
     "expr": "100 - (avg(node_filesystem_avail{instance=~\"$node\",mountpoint=\"/host/root/var/lib/docker\"}) * 100) / avg(node_filesystem_size{instance=~\"$node\",mountpoint=\"/host/root/var/lib/docker\"})\nor\n100 - (avg(node_filesystem_avail{instance=~\"$node\",mountpoint=\"/\",fstype=\"rootfs\"}) * 100) / avg(node_filesystem_size{instance=~\"$node\",mountpoint=\"/\",fstype=\"rootfs\"})",
     "legendFormat": "/var/lib/docker"
    }
   ]
  },
  { "title": "Basic CPU / Mem / Disk Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {},
    {
     "expr": "(((count(count(node_cpu{instance=~\"$node\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu{mode='idle',instance=~\"$node\"}[2m])))) * 100) / \ncount(count(node_cpu{instance=~\"$node\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "System uptime",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 6 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_time_seconds{instance=~\"$node\"} - node_boot_time{instance=~\"$node\"} > 0 or node_time{instance=~\"$node\"} - node_boot_time{instance=~\"$node\"}"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "singlestat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_memory_MemTotal{instance=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Total RootFS",
   "type": "singlestat",
   "description": "Total RootFS",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 6 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(node_filesystem_size{instance=~\"$node\",mountpoint=\"/host/root\"}) > 0 or avg(node_filesystem_size{instance=~\"$node\",mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Node unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 6 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_node_spec_unschedulable{node=\"$nodename\"})"
    }
   ]
  },
  {
   "title": "Ready status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kube_node_status_condition{node=~\"$nodename\", condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node CPU usage by pod",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(namespace_pod_name_container_name:container_cpu_usage_seconds_total:sum_rate{env=\"$ENV\",instance=~\"$node_ip:10250\"}) by (pod_name,namespace)",
       "legendFormat": "{{namespace}}: {{pod_name}}"
      }
     ]
    },
    {
     "title": "Memory usage by container",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_rss{env=\"$ENV\",instance=~\"$node_ip.+\",container_name!=\"\"}) by (namespace,container_name)",
       "legendFormat": "{{namespace}}: {{container_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Row title",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Panel Title",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "node:node_cpu_utilisation:avg1m{env=\"$ENV\",node=\"$nodename\"}",
       "legendFormat": "cpu-usage"
      },
      {
       "expr": "node:node_memory_bytes_Buffers:sum{env=\"$ENV\",node=\"$nodename\"}",
       "legendFormat": "mem-buffers"
      },
      {
       "expr": "node:node_memory_bytes_Cached:sum{env=\"$ENV\",node=\"$nodename\"}",
       "legendFormat": "mem-cached"
      },
      {
       "expr": "node:node_memory_bytes_Free:sum{env=\"$ENV\",node=\"$nodename\"}",
       "legendFormat": "mem-free"
      },
      {
       "expr": "node:node_memory_bytes_total:sum{env=\"$ENV\",node=\"$nodename\"}",
       "legendFormat": "mem-total"
      },
      {
       "expr": "node:node_memory_bytes_available:sum{env=\"$ENV\",node=\"$nodename\"}",
       "legendFormat": "mem-available"
      }
     ]
    }
   ]
  }
 ]
}