{
 "title": "Node / Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Cluster", "query": "label_values(up, env)" },
   { "name": "role", "label": "Role", "query": "i,m,w" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_namespace_pod:kube_pod_info:{node=~\"($env)($role)\\\\d{2}\"}, node)"
   },
   {
    "name": "ip",
    "query": "label_values(node_uname_info{nodename=~\"$node\", env=~\"$env\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cores",
   "type": "singlestat",
   "description": "node:node_num_cpu:sum",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_num_cpu:sum{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation:{node=\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_memory_bytes_total:sum{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_time_seconds{instance=~\"$ip:\\\\d+\"} - node_boot_time{instance=~\"$ip:\\\\d+\"})"
    }
   ]
  },
  {
   "title": "Unschedulable",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(kube_node_spec_unschedulable{node=\"$node\"})"
    }
   ]
  },
  {
   "title": "Readiness",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(kube_node_status_condition{node=~\"$node\", condition=\"Ready\",status=\"true\"})"
    }
   ]
  },
  {
   "title": "VM disk usage",
   "type": "singlestat",
   "description": "???",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "vmware_vm_disk_usage_average{vm_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "description": "Summary: 1- rate(node_cpu{mode=\"idle\"}[1m])\nLoad: node_load1 / node:node_num_cpu:sum",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg by (mode) (\r\n    rate(node_cpu{pod=~\"node-exporter.+\",mode!=\"idle\"}[1m])\r\n    * on (namespace, pod) group_left(node)\r\n    node_namespace_pod:kube_pod_info:{pod=~\"node-exporter.+\", node=~\"$node\"})",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=~\"$node\"})",
     "legendFormat": "summary"
    },
    {
     "expr": "avg(node:node_cpu_saturation_load1:{node=~\"$node\"})",
     "legendFormat": "load"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(node:node_memory_bytes_available:sum{node=\"$node\"})",
     "legendFormat": "available"
    },
    {
     "expr": "avg(node_memory_MemFree{instance=~\"$ip:\\\\d+\"})",
     "legendFormat": "free"
    },
    {
     "expr": "avg(node_memory_Cached{instance=~\"$ip:\\\\d+\"})",
     "legendFormat": "cached"
    },
    {
     "expr": "avg(node_memory_Buffers{instance=~\"$ip:\\\\d+\"})",
     "legendFormat": "buffers"
    }
   ]
  },
  {
   "title": "Filesystem usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by(namespace, pod, mountpoint)(\n  node_filesystem_avail{mountpoint=~\"(/host/root|/host/root/var/lib/docker)\"} \n  / node_filesystem_size\n  ) \n  * on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=~\"$node\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPU usage by pod",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg by (namespace, pod_name, container_name) (\n  rate(container_cpu_usage_seconds_total{job=\"kubelet\", image!=\"\", container_name!=\"\", instance=~\"$ip:\\\\d+\"}[5m])\n)",
     "legendFormat": "{{namespace}}: {{pod_name}}: {{container_name}}"
    }
   ]
  },
  {
   "title": "Memory usage by container",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_rss{env=\"$env\",instance=~\"$ip:\\\\d+\",container_name!=\"\"}) by (namespace, container_name)",
     "legendFormat": "{{namespace}}: {{container_name}}"
    }
   ]
  }
 ]
}