{
 "title": "Cluster / Quotas",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Cluster", "query": "label_values(up, env)" },
   {
    "name": "ns",
    "label": "Namespace",
    "query": "label_values(kube_pod_info{env=\"$env\"}, namespace)"
   },
   {
    "name": "resource",
    "label": "Resource",
    "query": "label_values(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\"}, resource)"
   },
   {
    "name": "type",
    "label": "Type",
    "query": "label_values(kube_resourcequota{env=\"$env\", namespace=~\"$ns\", resource=\"$resource\"}, type)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "singlestat",
   "description": "100 * sum(kube_resourcequota) / sum(kube_node_status_allocatable_cpu_cores)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * sum(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=\"limits.cpu\"})\n / sum(kube_node_status_allocatable_cpu_cores{node=~\"$env(w)\\\\d{2}\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "sum(avg by(node)(kube_node_status_allocatable_cpu_cores{node=~\"$env(w)\\\\d{2}\"}))"
    },
    {
     "expr": "sum(vmware_vm_num_cpu{vm_name=~\"$env(w)\\\\d{2}\"})"
    },
    {
     "expr": "sum(avg by (instance, namespace)(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=\"limits.cpu\"}))"
    },
    {
     "expr": "sum(avg by (instance, namespace)(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=\"requests.cpu\"}))"
    }
   ]
  },
  {
   "title": "Datastores",
   "type": "table",
   "description": "vmware_datastore_capacity_size",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "vmware_datastore_capacity_size{ds_name=~\".*-$env-ps\"}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "description": "100 * sum(kube_resourcequota) /\nsum(kube_node_status_allocatable_memory_bytes)",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 * sum(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=\"limits.memory\"}) /\nsum(kube_node_status_allocatable_memory_bytes{node=~\"$env(w)\\\\d{2}\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 4, "w": 9, "x": 3, "y": 4 },
   "targets": [
    {
     "expr": "sum(avg by (node)(kube_node_status_allocatable_memory_bytes{node=~\"$env(w)\\\\d{2}\"}))"
    },
    {
     "expr": "sum(vmware_vm_memory_max{vm_name=~\"$env(w)\\\\d{2}\"})"
    },
    {
     "expr": "sum(avg by (namespace)(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=\"limits.memory\"}))"
    },
    {
     "expr": "sum(avg by (namespace)(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=\"requests.memory\"}))"
    }
   ]
  },
  {
   "title": "Storage quota",
   "type": "table",
   "description": "sum(kube_resourcequota{type=\"hard\"})",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum by(resource)(avg by (instance,resource)(kube_resourcequota{env=\"$env\", type=\"hard\", namespace=~\"$ns\", resource=~\".+storage.+\"}))",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "CPU allocated by node",
   "type": "bargauge",
   "description": "100 * sum(kube_pod_container_resource_requests_cpu_cores) / \navg(kube_node_status_allocatable_cpu_cores)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(node)(avg by (node, pod)(kube_pod_container_resource_requests_cpu_cores{node=~\"$env(w).+\"})) / \navg by(node)(kube_node_status_allocatable_cpu_cores{node=~\"$env(w).+\"})\n* 100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "By namespace",
   "type": "graph",
   "description": "sum by (namespace)(kube_resourcequota)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace)(avg by (instance, namespace)(kube_resourcequota{env=\"$env\", type=\"$type\", namespace=~\"$ns\", resource=\"$resource\"}))",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory allocated by node",
   "type": "bargauge",
   "description": "100 * sum(kube_pod_container_resource_requests_memory_bytes) /\navg(kube_node_status_allocatable_memory_bytes)",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum  by(node)(avg by (node, pod)(kube_pod_container_resource_requests_memory_bytes{node=~\"$env(w).+\"})) /\navg  by(node)(kube_node_status_allocatable_memory_bytes) * 100",
     "legendFormat": "{{node}}"
    }
   ]
  }
 ]
}