{
 "title": "Cluster / Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "env", "label": "Cluster", "query": "label_values(up, env)" },
   { "name": "role", "label": "Role", "query": "i,m,w" },
   {
    "name": "node",
    "label": "Node",
    "query": "label_values(node_namespace_pod:kube_pod_info:{node=~\"($env)($role)\\\\d{2}\"}, node)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU usage",
   "type": "singlestat",
   "description": "1 - avg(rate(node_cpu{mode=\"idle\"}[1m]))",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_utilisation:avg1m{node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "singlestat",
   "description": "1 - (node:node_memory_bytes_available:sum / node:node_memory_bytes_total:sum)",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_memory_utilisation_2:{env=\"$env\"}) * 100"
    }
   ]
  },
  {
   "title": "Load average 1min",
   "type": "singlestat",
   "description": "sum by (node) (node_load1)  /  node:node_num_cpu:sum",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_cpu_saturation_load1:{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Vmem I/O",
   "type": "singlestat",
   "description": "1e3 * sum by (node) ((\n  rate(node_vmstat_pgpgin[1m]) + \n  rate(node_vmstat_pgpgout[1m])\n))",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "bps",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_memory_swap_io_bytes:sum_rate{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "singlestat",
   "description": "irate(node_disk_io_time_weighted[1m])\nhttps://www.kernel.org/doc/Documentation/iostats.txt",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node:node_disk_saturation:avg_irate{node=~\"$node\"})"
    }
   ]
  },
  {
   "title": "Datastore usage",
   "type": "singlestat",
   "description": "1 - min(vmware_datastore_freespace_size / \nvmware_datastore_capacity_size)",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "100 - min(vmware_datastore_freespace_size{ds_name=~\"(sas|ssd)-$env-.+\"} / vmware_datastore_capacity_size{ds_name=~\"(sas|ssd)-$env-.+\"}) * 100"
    }
   ]
  },
  {
   "title": "By node",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "avg by(node)(node:node_cpu_utilisation:avg1m{node=~\"$node\"})"
    },
    {
     "expr": "avg by(node)(node:node_memory_utilisation_2:{node=~\"$node\"})"
    },
    {
     "expr": "avg by(node)(node:node_cpu_saturation_load1:{node=~\"$node\"})"
    },
    {
     "expr": "avg by(node)(node:node_memory_swap_io_bytes:sum_rate{node=~\"$node\"})"
    },
    {
     "expr": "avg by(node)(node:node_disk_saturation:avg_irate{node=~\"$node\"})"
    },
    {
     "expr": "avg by(node)(min by(namespace, pod)(node:node_filesystem_avail:) * on (namespace, pod) group_left (node) node_namespace_pod:kube_pod_info:{node=~\"$node\"})"
    }
   ]
  }
 ]
}