- hosts: localhost
  vars_files:
    - "vars/defaults.yaml"
  become: true
  gather_facts: false
  become_user: root
  tasks:
    - name: Generating HOT SLA template
      template:
        src: hot-template.j2
        dest: ./sla-stack.yaml
