---
kind: "Template"
apiVersion: "v1"
metadata:
  name: "cronjob-ldap-group-sync"
  annotations:
    description: "Scheduled Task to Perform LDAP Group Synchronization"
    iconClass: "icon-shadowman"
    tags: "management,cronjob,ldap,group,sync"
objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ldap-config
    labels:
      template: "cronjob-ldap-group-sync"
  data:
    ldap-sync.yml: |
      kind: LDAPSyncConfig
      apiVersion: v1
      url: ${LDAP_URL}
      insecure: true
      bindDN: ${LDAP_BIND_DN}
      bindPassword: ${LDAP_BIND_PASSWORD}
      rfc2307:
          groupsQuery:
              baseDN: ${LDAP_GROUPS_SEARCH_BASE}
              scope: sub
              derefAliases: never
              filter: ${LDAP_GROUPS_FILTER}
              pageSize: 0
          groupUIDAttribute: dn
          groupNameAttributes: [ cn ]
          groupMembershipAttributes: [ member ]
          usersQuery:
              baseDN: ${LDAP_USERS_SEARCH_BASE}
              scope: sub
              derefAliases: never
              pageSize: 0
          userUIDAttribute: dn
          userNameAttributes: [ sAMAccountName ]
          tolerateMemberNotFoundErrors: true
          tolerateMemberOutOfScopeErrors: true
- kind: "CronJob"
  apiVersion: "batch/v1beta1"
  metadata:
    name: "${CRONJOB_NAME}"
    labels:
      template: "cronjob-ldap-group-sync"
  spec:
    schedule: "${SCHEDULE}"
    concurrencyPolicy: "Forbid"
    successfulJobsHistoryLimit: "${{SUCCESS_JOBS_HISTORY_LIMIT}}"
    failedJobsHistoryLimit: "${{FAILED_JOBS_HISTORY_LIMIT}}"
    jobTemplate:
      spec:
        template:
          spec:
            containers:
              - name: "${CRONJOB_NAME}"
                image: "${IMAGE}:${IMAGE_TAG}"
                command:
                  - "/bin/sh"
                  - "-c"
                  - "oc adm groups sync --sync-config=/etc/conf.d/ldap-group-sync.yaml || :"
                volumeMounts:
                  - mountPath: "/etc/conf.d"
                    name: "ldap-sync-volume"
            volumes:
              - configMap:
                  items:
                    - key: ldap-sync.yml
                      path: ldap-group-sync.yaml
                  name: ldap-config
                name: ldap-sync-volume
            restartPolicy: "Never"
            terminationGracePeriodSeconds: 30
            activeDeadlineSeconds: 500
            dnsPolicy: "ClusterFirst"
            serviceAccountName: "${JOB_SERVICE_ACCOUNT}"
            serviceAccount: "${JOB_SERVICE_ACCOUNT}"
- kind: ClusterRole
  apiVersion: v1
  metadata:
    name: ldap-group-syncer
    labels:
      template: "cronjob-ldap-group-sync"
  rules:
    - apiGroups:
        - ""
        - user.openshift.io
      resources:
        - groups
      verbs:
        - get
        - list
        - create
        - update
- kind: ClusterRoleBinding
  apiVersion: v1
  groupNames: null
  metadata:
    name: system:ldap-group-syncers
    labels:
      template: "cronjob-ldap-group-sync"
  roleRef:
    name: ldap-group-syncer
  subjects:
  - kind: ServiceAccount
    name: ${JOB_SERVICE_ACCOUNT}
  userNames:
  - system:serviceaccount:${NAMESPACE}:${JOB_SERVICE_ACCOUNT}
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: ${JOB_SERVICE_ACCOUNT}
    labels:
      template: "cronjob-ldap-group-sync"
parameters:
  - name: "NAMESPACE"
    displayName: "Namespace"
    description: "Name of the Namespace where to deploy the Scheduled Job"
    value: "default"
    required: true
  - name: "CRONJOB_NAME"
    displayName: "CronJob Name"
    description: "Name of the Scheduled Job to Create."
    value: "cronjob-ldap-group-sync"
    required: true
  - name: "SCHEDULE"
    displayName: "Cron Schedule"
    description: "Cron Schedule to Execute the Job"
    value: "@hourly"
    required: true
  - name: "SUCCESS_JOBS_HISTORY_LIMIT"
    displayName: "Successful Job History Limit"
    description: "The number of successful jobs that will be retained"
    value: "5"
    required: true
  - name: "FAILED_JOBS_HISTORY_LIMIT"

Ватолин Алексей Владимирович, [03.06.19 13:01]
displayName: "Failed Job History Limit"
    description: "The number of failed jobs that will be retained"
    value: "5"
    required: true
  - name: "LDAP_URL"
    displayName: "LDAP Server URL"
    description: "URL of you LDAP server"
    required: true
  - name: "LDAP_BIND_DN"
    displayName: "LDAP Bind User's DN"
    description: "The Full DN for the user you wish to use to authenticate to LDAP"
    required: true
  - name: "LDAP_BIND_PASSWORD"
    displayName: "LDAP Bind User's password"
    description: "Password for the LDAP_BIND_DN user"
    required: true
  - name: "LDAP_GROUPS_SEARCH_BASE"
    displayName: "Group search query"
    description: "Location in LDAP tree where you will find groups"
    required: true
    value: "cn=groups,cn=accounts,dc=myorg,dc=example,dc=com"
  - name: "LDAP_GROUPS_FILTER"
    displayName: "Group Filter"
    description: "LDAP Filter to use when deciding which groups to sync into OpenShift"
    required: true
    value: "(&(objectclass=ipausergroup)(memberOf=cn=openshift-users,cn=groups,cn=accounts,dc=myorg,dc=example,dc=com))"
  - name: "LDAP_USERS_SEARCH_BASE"
    displayName: "User search query"
    description: "Location in LDAP tree where you will find users"
    required: true
    value: "cn=users,cn=accounts,dc=myorg,dc=example,dc=com"
  - name: "IMAGE"
    displayName: "Image"
    description: "Image to use for the container."
    required: true
    value: "nexus-registry.s7.aero:18117/widerin/openshift-cli"
  - name: "IMAGE_TAG"
    displayName: "Image Tag"
    description: "Image Tag to use for the container."
    required: true
    value: "v3.11.0"
labels:
  template: "cronjob-ldap-group-sync"
